# Kafka Consumer

spring:
  application:
    name: test-consumer
## Due to programmatic config, no need to these!
#  kafka:
#    consumer:
#      auto-offset-reset: earliest
#      group-id: simple-messaging
