# KAFKA STREAM CONSUMER

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
          consumer-properties:
            auto-offset-reset: earliest
      bindings:
        input:
          binder: kafka
          destination: test
          content-type: text/plain
          group: input-group-1